### ISSUE TITLE
Crash recovery

### ISSUE THREAD

**Issue by slav** [Bobris/BTDB#45]
Hello. I've stumbled on your DB while researching LMDB usage from .NET and have a couple of questions:

1. LMDB has very good recovery story. If it crashes before write transaction is finished the DB remains in consistent state. How about BTDB? How is the data structured in the DB and how does it behave under crash conditions? Is limitation, similar to LMDB, just a single writer too?
2. Have you compared BTDB speed with LMDB?

**Comment by Bobris** [comment]
1. BTDB recovery is also perfect (simplicity is what makes it working), it just takes time after restart to load all keys to memory together with replay transaction log from from last "KVI" (key value index file). And yes there is equal limitation of single writer.
2. Not enough to disclose any results (in past LMDB was slower in .Net because of overheads in LMDB wrappers). Also performance profile is very different. BTDB writes are very cheap even short ones.

BTDB KeyValue Db is not met to be backed directly by AzureBlobs (it would be too slow). Currently we do only backup in background, so when server restarts it lazily downloads content from Blobs.
We use CQRS architecture with one event stream. We directly store event stream in Azure blobs, but we now moving store them in Kafka, so BTDB is used for event serialization.

So all servers are equal, they all have locally stored their own copy of DB for extreme speed. And all changes go "transactionally" though event store in Kafka.
